"""
Statistical Tests for:
"Discovering Lie-Algebraic Action Spaces for Sample-Efficient
 Reinforcement Learning in Latent Spaces"
ICECCME 2026

Reads per-seed results from: results/exp2_per_seed_results.json
(generated by run_full_experiments.py)

Tests: Welch's t-test (pairwise, unequal variance, n=5 seeds)
"""

import json
import numpy as np
from scipy import stats
from pathlib import Path

# -----------------------------------------------------------------------------
# STEP 1: LOAD PER-SEED RESULTS FROM JSON
# -----------------------------------------------------------------------------
JSON_PATH = Path("results/exp2_per_seed_results.json")

if not JSON_PATH.exists():
    raise FileNotFoundError(
        f"\n[ERROR] {JSON_PATH} not found.\n"
        "Run 'python run_full_experiments.py' first to generate it.\n"
    )

with open(JSON_PATH) as f:
    log = json.load(f)

seed_results = log["per_seed_success_pct"]

print("=" * 62)
print("LOADED FROM JSON")
print("=" * 62)
print(f"  Source:    {JSON_PATH}")
print(f"  Timestamp: {log.get('timestamp', 'unknown')}")
config = log.get("config", {})
print(f"  Config:    d={config.get('d')}, "
      f"episodes={config.get('n_episodes')}, "
      f"seeds={config.get('n_seeds')}")

# -----------------------------------------------------------------------------
# STEP 2: VERIFY -- computed stats vs paper-reported values
# Uses sample std (ddof=1) to match how the paper reports mean +/- std
# -----------------------------------------------------------------------------
reported = {
    "Discovered":   (47.3, 7.7),
    "Ground_Truth": (47.3, 5.3),
    "PCA":          (36.0, 3.3),
    "Full":         (36.0, 5.7),
    "Random":       (32.0, 5.4),
}

print()
print("=" * 62)
print("VERIFICATION: Computed vs paper-reported mean +/- std")
print("=" * 62)

for method, vals in seed_results.items():
    arr = np.array(vals)
    if len(arr) != 5:
        print(f"  [WARNING] {method}: expected 5 seeds, got {len(arr)}")
        continue
    mu  = arr.mean()
    std = arr.std(ddof=1)
    mu_r, std_r = reported.get(method, (None, None))
    if mu_r is not None:
        close = abs(mu - mu_r) < 2.0 and abs(std - std_r) < 2.0
        flag  = "OK" if close else "! DIFFERS FROM PAPER"
        print(f"  [{flag}]  {method:<15} "
              f"Paper: {mu_r:.1f} +/- {std_r:.1f}  |  "
              f"Actual: {mu:.1f} +/- {std:.1f}  |  "
              f"Seeds: {vals}")
    else:
        print(f"  [?]  {method:<15} Actual: {mu:.1f} +/- {std:.1f}  Seeds: {vals}")

# -----------------------------------------------------------------------------
# STEP 3: WELCH'S T-TESTS
# -----------------------------------------------------------------------------
disc = np.array(seed_results["Discovered"])
gt   = np.array(seed_results["Ground_Truth"])
pca  = np.array(seed_results["PCA"])
full = np.array(seed_results["Full"])
rand = np.array(seed_results["Random"])

def cohens_d(a, b):
    """Pooled Cohen's d using sample std (ddof=1)."""
    pooled = np.sqrt((a.std(ddof=1)**2 + b.std(ddof=1)**2) / 2)
    return (a.mean() - b.mean()) / pooled if pooled > 0 else 0.0

print()
print("=" * 62)
print("WELCH'S T-TESTS (two-tailed, unequal variance)")
print("=" * 62)
print(f"\n  {'Comparison':<33} {'t':>7} {'p':>8}  {'Sig':>5}  {'Cohen d':>8}")
print("  " + "-" * 62)

comparisons = [
    ("Discovered vs Ground Truth", disc, gt),
    ("Discovered vs PCA",          disc, pca),
    ("Discovered vs Full",         disc, full),
    ("Discovered vs Random",       disc, rand),
]

results = {}
for label, a, b in comparisons:
    t_stat, p_val = stats.ttest_ind(a, b, equal_var=False)
    d = cohens_d(a, b)
    sig = ("***" if p_val < 0.001 else
           "**"  if p_val < 0.01  else
           "*"   if p_val < 0.05  else "n.s.")
    results[label] = (t_stat, p_val, d, sig)
    print(f"  {label:<33} {t_stat:>7.3f} {p_val:>8.4f}  {sig:>5}  {d:>8.3f}")

print()
print("  Significance: *** p<0.001  ** p<0.01  * p<0.05  n.s. = not significant")
print("  Note: n=5 seeds gives low power -- report Cohen's d alongside p-value.")

# -----------------------------------------------------------------------------
# STEP 4: LATEX SNIPPET
# -----------------------------------------------------------------------------
def fmt_p(p):
    if p < 0.001: return "$p < 0.001$"
    return f"$p = {p:.3f}$"

t1, p1, d1, s1 = results["Discovered vs Ground Truth"]
t2, p2, d2, s2 = results["Discovered vs PCA"]
t3, p3, d3, s3 = results["Discovered vs Full"]
t4, p4, d4, s4 = results["Discovered vs Random"]

pca_verb  = "significantly outperforms" if p2 < 0.05 else "outperforms (trend,"
pca_p_str = fmt_p(p2) if p2 < 0.05 else fmt_p(p2) + ")"
rand_verb = "significantly outperforms" if p4 < 0.05 else "outperforms"

print()
print("=" * 62)
print("LATEX SNIPPET -- paste into Main Results paragraph")
print("=" * 62)
print(f"""
Welch's $t$-tests (two-tailed, $n=5$ seeds per method) confirm
that Discovered {pca_verb} PCA ({pca_p_str},
Cohen's $d={d2:.2f}$) and {rand_verb} Random ({fmt_p(p4)},
Cohen's $d={d4:.2f}$), while showing no significant difference
from Ground Truth ({fmt_p(p1)}), consistent with the hypothesis
that SVD-based discovery recovers the true Lie algebra's action space.
""")

# -----------------------------------------------------------------------------
# STEP 5: SAVE TEST RESULTS TO JSON
# -----------------------------------------------------------------------------
out = {
    "source_json": str(JSON_PATH),
    "tests": {
        label: {
            "t":                round(float(t), 4),
            "p":                round(float(p), 4),
            "cohens_d":         round(float(d), 3),
            "significant_0.05": bool(p < 0.05),
            "sig_label":        s,
        }
        for label, (t, p, d, s) in results.items()
    }
}

out_path = Path("results/statistical_test_results.json")
with open(out_path, "w") as f:
    json.dump(out, f, indent=2)
print(f"Test results saved: {out_path}")
